### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yangdaowu** [paxbun/Conv-TasNet#2]
Hello, I have happened when I run tran.py.
Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated. [[{{node PyFunc}}]]

**Comment by paxbun** [comment]
The error you encountered occurs when an error occurs during executing a function dynamically generated by TensorFlow. Could you please attach the entire error message? I cannot give you any information or suggestion about the issue.

**Comment by yangdaowu** [comment]
Decoding Audio [14] of subset train...
100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.24s/it]
2022-05-07 13:28:43.997294: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 209715200 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    app.run(main)
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "main.py", line 80, in main
    model.fit(train, validation_data=val)
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/user/anaconda3/envs/MSS/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
         [[node conv_tas_net/separation/conv_block/conv1d_2/conv1d (defined at /home/user/PycharmProjects/wavnet/Conv-TasNet-master/conv_tasnet/layers.py:166) ]] [Op:__inference_train_function_28552]

Function call stack:
train_function

2022-05-07 13:28:44.496904: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]

**Comment by paxbun** [comment]
The point is in this line:

> tensorflow.python.framework.errors_impl.UnimplementedError: Fused conv implementation does not support grouped convolutions for now.

This repo was made with TensorFlow 2.3. What version of TF are you using now?

**Comment by yangdaowu** [comment]
![image](https://user-images.githubusercontent.com/64669901/167240027-1a6259b4-f67d-47b3-a4ce-b4bdf0735db3.png)
I'll try to reconfigure the environment

**Comment by paxbun** [comment]
Sorry for making you spend time on this repo, but since I have not been maintaining this repo for more than a year, I can't give you any advice that will be helpful. I haven't spent much time making this repo's code quality better, so there might be some inconsistencies between the source code uploaded to GitHub and the actual code I used on my server. If you have any questions about my implementation, feel free to ask me :)
